version: '3.6'
services:
  crypto_gateway:
    restart: always
    build: './gateway'
    network_mode: "host"
    depends_on:
      - crypto_engine
      - geth-eth-node
    environment:
      ETH_RPC_ENDPOINT: ${ETH_RPC_ENDPOINT:-http://127.0.0.1:8555}
      BCOIN_API_KEY: ${BCOIN_API_KEY}
      CRYPTOPAY_BTC_XPUB: ${CRYPTOPAY_BTC_XPUB}
      CRYPTOPAY_ETH_XPUB: ${CRYPTOPAY_ETH_XPUB}
      CRYPTOPAY_SECRET: ${CRYPTOPAY_SECRET:-secret}
      BCOIN_ENDPOINT: ${BCOIN_ENDPOINT:-http://127.0.0.1:18332}
      BCOIN_WALLET_ENDPOINT: ${BCOIN_WALLET_ENDPOINT:-http://127.0.0.1:18334}
      UNCHAINED_CRYPTOPAY_WEBHOOK_PATH: ${UNCHAINED_CRYPTOPAY_WEBHOOK_PATH:-http://127.0.0.1:4010/payment/cryptopay}
      UNCHAINED_CRYPTOPAY_PRICING_WEBHOOK_PATH: ${UNCHAINED_CRYPTOPAY_PRICING_WEBHOOK_PATH:-http://127.0.0.1:4010/pricing/cryptopay}
      UNCHAINED_GRAPHQL_ENDPOINT: ${UNCHAINED_GRAPHQL_ENDPOINT:-http://127.0.0.1:4010/graphql}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_HOST: ${REDIS_HOST:-127.0.0.1}
    env_file:
      - .env

  crypto_storefront:
    build: ./storefront
    ports:
      - "3000:3000"
    depends_on:
      - crypto_engine
    restart: on-failure
    environment:
      UNCHAINED_ENDPOINT: http://crypto_engine:4010/graphql

  crypto_engine:
    build: ./engine
    ports:
      - "4010:4010"
    environment:
      MONGO_URL: ${MONGO_URL:-mongodb://my-mongoDB}
      ROOT_URL: ${ROOT_URL:-http://localhost:4010}
      EMAIL_WEBSITE_NAME: ${EMAIL_WEBSITE_NAME:-Unchained}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@unchained.local}
      UNCHAINED_SEED_PASSWORD: ${UNCHAINED_SEED_PASSWORD:-password}
      EMAIL_WEBSITE_URL: ${EMAIL_WEBSITE_URL:-http://localhost:4010}
      CRYPTOPAY_SECRET: ${CRYPTOPAY_SECRET:-secret}
      CRYPTOPAY_BTC_XPUB: ${CRYPTOPAY_BTC_XPUB}
      CRYPTOPAY_ETH_XPUB: ${CRYPTOPAY_ETH_XPUB}
      CRYPTOPAY_WEBHOOK_PATH: ${CRYPTOPAY_WEBHOOK_PATH:-/payment/cryptopay}
      CRYPTOPAY_PRICING_WEBHOOK_PATH: ${CRYPTOPAY_PRICING_WEBHOOK_PATH:-/pricing/cryptopay}
    env_file:
      - .env
    healthcheck:
      disable: true
    # healthcheck:
    #   test: >-
    #     curl -XPOST http://localhost:4010/graphql -H 'content-type: application/json' --data-raw '{"operationName":null,"variables":{},"query":"{shopInfo{_id}}"}' || exit 1
    #   start_period: 3s
    #   timeout: 3s
    depends_on:
      - my-mongoDB

  my-mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --loglevel debug
    volumes:
      - cache:/data
      
  geth-eth-node:
    image: ethereum/client-go
    restart: on-failure
    ports:
      - "8555:8555"
      - "8551:8551"
    command:
      - --goerli
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --syncmode=snap
      - --http.port=8555
      - --ipcdisable
    volumes:
      - geth-goerli:/.goerli
      - $HOME/ethereum:/root

  nimbus-eth-consensus-node:
    image: statusim/nimbus-eth2:multiarch-v22.7.0
    restart: unless-stopped
    stop_grace_period: 1m
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 127.0.0.1:9190:9190/tcp
      - 127.0.0.1:8008:8008/tcp
    #   - "127.0.0.1:5052:5052"
    command:
      - --network=prater
      - --data-dir=/home/user/nimbus-eth2/build/data/shared_prater_0
      - --web3-url=ws://geth-eth-node:8551
      # --jwt-secret=/root/.geth/.ethereum/prater/geth/jwtsecret
      - --log-level=info
      - --tcp-port=9000
      - --udp-port=9000
      - --rpc
      - --rpc-address=0.0.0.0
      - --rpc-port=9190
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=8008
    volumes:
      - $HOME/.nimbus:/home/user/nimbus-eth2/build/data
      - $HOME/ethereum:/root/.geth
volumes:
  db-data: {}
  mongo-config: {}
  cache:
    driver: local
  geth-goerli: {}
