version: '3.6'
services:
  crypto_gateway:
     restart: always
     build: './gateway'
     network_mode: "host"        
     depends_on:
      - crypto_engine
      - geth-eth-node
     environment:
       ETH_RPC_ENDPOINT : http://127.0.0.1:8545
     env_file:
      - './.env.gateway'
    
  crypto_storefront:
    build: ./storefront
    ports:
      - "3000:3000"
    depends_on:
      - crypto_engine
    restart: on-failure
    environment:
      UNCHAINED_ENDPOINT : http://crypto_engine:3000/graphql
  crypto_engine:
    build: ./engine
    ports:
      - "4010:3000"
    environment:
      - MONGO_URL=mongodb://my-mongoDB
    env_file:
      - './.env.engine'
    healthcheck:
      test: >-
        curl -f http://localhost:3000/graphql/healthcheck || exit 1
      start_period: 10s
      timeout: 5s
    depends_on:
      - my-mongoDB
  my-mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --loglevel debug
    volumes: 
      - cache:/data
  geth-eth-node: 
    image: ethereum/client-go
    restart: on-failure
    ports:
      - "8545:8545"
    command:  
      - --networkid=${GETH_NETWORK_ID:-5}
      - --http
      - --http.api
      - "eth,net,web3"
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --ws
      - --ws.origins=*
      - --ws.addr=0.0.0.0
      - --ws.api
      - "eth,net,web3"
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
    volumes:                                                                 
      - geth-goerli:/.goerli
volumes:
  db-data: {}
  mongo-config: {}
  cache:
    driver: local
  geth-goerli: {}
