version: '3.6'
services:
  crypto_gateway:
     restart: on-failure
     build: './gateway'
     network_mode: "host"        
     depends_on:
      - crypto_engine
     env_file:
      - './.env.gateway'
  crypto_storefront:
    build: ./storefront
    ports:
      - "3000:3000"
    depends_on:
      - crypto_engine
    restart: on-failure
    environment:
      UNCHAINED_ENDPOINT : http://crypto_engine:3000/graphql
  crypto_engine:
    build: ./engine
    ports:
      - "4010:3000"
    env_file:
      - './.env.engine'
    healthcheck:
      test: >-
        curl -f http://localhost:3000/graphql/healthcheck || exit 1
      start_period: 10s
      timeout: 5s
    depends_on:
      - my-mongoDB
  my-mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
  redis:
    image: redis:6.2-alpine
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --loglevel debug
    volumes: 
      - cache:/data
volumes:
  db-data:
  mongo-config:
  cache:
    driver: local
