

currencies:
  eth:
    rpc-endpoint: ${ETH_RPC_ENDPOINT}
    xpub: ${CRYPTOPAY_ETH_XPUB}
    poa-testnet: True # Running on a a testnet with PoA
    init-block-history: 1000 # How many blocks in the past to consider on the first run
    link-feed-registry-addr: "0xAa7F6f7f507457a1EE157fE97F6c7DB2BEec5cD0" # Chainlink Feed Registry Address: https://docs.chain.link/docs/feed-registry/
  btc:
    bcoin-endpoint: ${BCOIN_ENDPOINT}
    wallet-endpoint: ${BCOIN_WALLET_ENDPOINT}
    bcoin-apikey: ${BCOIN_API_KEY}
    xpub: ${CRYPTOPAY_BTC_XPUB}

unchained:
  transaction-webhook-url: ${ROOT_URL}${CRYPTOPAY_WEBHOOK_PATH}
  price-webhook-url: ${ROOT_URL}${CRYPTOPAY_PRICING_WEBHOOK_PATH}
  graphql-endpoint: ${UNCHAINED_GRAPHQL_ENDPOINT}
  secret: ${CRYPTOPAY_SECRET}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}